### ISSUE TITLE
Add encode/decode method which accepts argument names

### ISSUE THREAD

**Issue by frozeman** [ethereumjs/ethereumjs-abi#38]
It would be good to return names of named return values, as well as in the future incorporate returning structs: https://github.com/ethereum/EIPs/issues/50

To make that possible we need a function which accepts the full in/outPut types including names, and returns those as object

```js
// returns the encoded binary (as a Buffer) data to be sent
var encoded = abi.typesEncode([ {name: "myNumber", type: "uint256"} ], [ 10 ])
> "0x0000000000000000000000000000000000000000000000000000000000000a"

// returns the decoded array of arguments
var decoded = abi.typesDecode([{name: "myAddress", type: "address"},  {type: "uint256"} ,{name: "myNumber", type: "uint256"}   ], data)
> {
      myAddress: '0x12000000000000000000000000000000000000034',
      0: 5, // if no name is given use indexes
      myNumber: 10
}
```

The question is only if *single return values* which have a name, should be returned as objects or the data only.

Structs as described in https://github.com/ethereum/EIPs/issues/50 would be returned the same way, as multiple named return values.

**Comment by VoR0220** [comment]
Sorry, just saw this, I'm sure you've had changing thoughts on this since then, but I just want to add to this and say that there's really no point to worrying about names in the encoding process. They only really matter in the decoding process. If you want to add it for that, by all means, put the time in there but I think it would be an unwise use of time to provide name support for encoding portion. That's all!

**Comment by holgerd77** [comment]
Only one comment arguing in a not-necessary direction and no further discussion for 6+ months, will close.
